[package]
name = "init"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
colored = { workspace = true }
crossterm = { workspace = true }
rustix = { workspace = true, features = ["system"] }

tl = { workspace = true }
logger = { workspace = true }
