[package]
name = "init"
version = "0.1.0"
edition.workspace = true

[dependencies]
prelude.workspace = true

serde.workspace = true
crossterm.workspace = true
rustix = { workspace = true, features = ["system"] }

tl.workspace = true

[lints]
workspace = true
